export const API_ROUTES = {
  PLAY: '/api/play/get-play',
  LOGIN: '/api/global/login',
  REGISTER: `/api/user/signup-user`,
  GET_QUESTION: `/api/user/get-question`,
  SECURITY_ANSWER: `/api/user/:userId/security-answers`,
  VALUES: '/api/array/items',
  GET_ALL_USERS: '/api/user/get-users-data',
  UPDATE_USERS: '/api/user/:itemId/update-user',
  UPDATE_VALUES: `/api/array/item-update/:userId`,
  FILTER_LEVEL: `/api/play/by-level/:level`,
  TIME: '/api/time/get-time',
  GET_SESSION_WORD: '/api/mcq/get-session-words',
  GET_ALL_MCQ: `/api/mcq`,
  POST_JUMBLE_WORDS: `/api/mcq/add-words`,
  GET_SINGLE_USER: `/api/user/get-user/:userId`,
  POST_ADD_PLAY_DATA: `/api/play`,
  FILTER_PLAY_LEVELS: `/api/play/levels`,

  ADMIN: {
    PROFILE: `/api/admin/admin-data`,
    UPDATE_PROFILE: `/api/admin/update-admin/:adminId`,
    GET_USERS_LIST: `/api/user/get-users`,
    GET_SINGLE_USER: `/api/user/get-user/:userId`,
    USER_REPORT: `/api/user/download-user-play-pdf`,
    UPDATE_USER: `/api/user/:userId/update-user`,
    DELETE_USER: `/api/user/:userId/delete-user`,
    GET_QUESTIONS: `/api/user/get-question`,
    ADD_QUESTION: `/api/admin/add-question`,
    UPDATE_QUESTION: `/api/admin/security-questions-update/:questionId`,
    DELETE_QUESTION: `/api/admin/security-questions-delete/:questionId`,
    GET_JUMBLE_WORDS: `/api/mcq/`,
    DELETE_JUMBLE_WORDS: `/api/mcq/delete/:id`,
    POST_JUMBLE_WORDS: `/api/mcq/add-words`,
    UPDATE_JUMBLE_WORDS: `/api/mcq/update/:id`,

    POST_BG_IMAGES: '/api/admin/bg-img',
    GET_BG_IMAGES: '/api/admin/bg-img',
    PATCH_BG_IMAGES: '/api/admin/bg-img/:id',
    DELETE_BG_IMAGES: '/api/admin/bg-img/:id',
  },
}
